apiVersion: v1
kind: Service
metadata:
  name: audible-download-service
spec:
  type: NodePort
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5003
  selector:
    io.kompose.service: audible-download-service