apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bookings-secondary
  name: bookings-secondary
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookings-secondary
  template:
    metadata:
      labels:
        io.kompose.service: bookings-secondary
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-7:bookings-secondary
          name: bookings-secondary
          ports:
            - containerPort: 5004
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred