apiVersion: v1
kind: Service
metadata:
  name: bookings-secondary
spec:
  type: NodePort
  ports:
    - name: "5004"
      port: 5004
      targetPort: 5004
  selector:
    io.kompose.service: bookings-secondary