apiVersion: v1
kind: Service
metadata:
  name: mobile-client
spec:
  type: LoadBalancer
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: mobile-client
