version: '3'

services:
    orders:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-1-food-delivery-example-2:orders
        build: 
            context: './services/orders/'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"
    auth:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/case-study-1-food-delivery-example-2:auth
        build: 
            context: './services/auth'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"


