version: '3'

services:
    movies:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:movies
        build:
            context: './services/movies/'
            dockerfile: './Dockerfile'
        ports:
            - "5001:5001"
    showtimes:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:showtimes
        build: 
            context: './services/showtimes'
            dockerfile: './Dockerfile'
        ports:
            - "5002:5002"
    bookings-primary:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:bookings-primary
        build: 
            context: './services/bookings-primary'
            dockerfile: './Dockerfile'
        ports:
            - "5003:5003"
    bookings-secondary:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:bookings-secondary
        build: 
            context: './services/bookings-secondary'
            dockerfile: './Dockerfile'
        ports:
            - "5004:5004"
    users:
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:users
        build: 
            context: './services/users'
            dockerfile: './Dockerfile'
        ports:
            - "5000:5000"

