apiVersion: v1
kind: Service
metadata:
  name: global-recommendations
spec:
  type: NodePort
  ports:
    - name: "5008"
      port: 5008
      targetPort: 5008
  selector:
    io.kompose.service: global-recommendations
