apiVersion: v1
kind: Service
metadata:
  name: content-delivery-service
spec:
  type: NodePort
  ports:
    - name: "5002"
      port: 5002
      targetPort: 5002
  selector:
    io.kompose.service: content-delivery-service