apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: content-delivery-engine
  name: content-delivery-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: content-delivery-engine
  template:
    metadata:
      labels:
        io.kompose.service: content-delivery-engine
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/audible:content-delivery-engine
          name: content-delivery-engine
          ports:
            - containerPort: 5001
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred