apiVersion: v1
kind: Service
metadata:
  name: content-delivery-engine
spec:
  type: NodePort
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: content-delivery-engine