apiVersion: v1
kind: Service
metadata:
  name: api-server
spec:
  type: LoadBalancer
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5001
  selector:
    io.kompose.service: api-server
