apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bookings-primary
  name: bookings-primary
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookings-primary
  template:
    metadata:
      labels:
        io.kompose.service: bookings-primary
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/cinema-6:bookings-primary
          name: bookings-primary
          ports:
            - containerPort: 5003
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred