apiVersion: v1
kind: Service
metadata:
  name: bookings-primary
spec:
  type: NodePort
  ports:
    - name: "5003"
      port: 5003
      targetPort: 5003
  selector:
    io.kompose.service: bookings-primary