apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: telemetry
  name: telemetry
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: telemetry
  template:
    metadata:
      labels:
        io.kompose.service: telemetry
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/netflix:telemetry
          name: telemetry
          ports:
            - containerPort: 5004
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred