apiVersion: v1
kind: Service
metadata:
  name: user-profile
spec:
  type: NodePort
  ports:
    - name: "5010"
      port: 5010
      targetPort: 5010
  selector:
    io.kompose.service: user-profile
