apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        io.kompose.service: db-primary
    name: db-primary
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: db-primary
    template:
        metadata:
            labels:
                io.kompose.service: db-primary
        spec:
            containers:
                - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:db-primary
                    name: db-primary
                    ports:
                        - containerPort: 5003
                    imagePullPolicy: IfNotPresent
            restartPolicy: Always
            imagePullSecrets:
                - name: regcred