apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db-secondary
  name: db-secondary
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-secondary
  template:
    metadata:
      labels:
        io.kompose.service: db-secondary
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:db-secondary
          name: db-secondary
          ports:
            - containerPort: 5004
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred