apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: bookmarks
  name: bookmarks
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bookmarks
  template:
    metadata:
      labels:
        io.kompose.service: bookmarks
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/netflix:bookmarks
          name: bookmarks
          ports:
            - containerPort: 5003
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred