apiVersion: v1
kind: Service
metadata:
    name: requestmapper
spec:
    type: NodePort
    ports:
        - name: "5002"
            port: 5002
            targetPort: 5002
    selector:
        io.kompose.service: requestmapper