apiVersion: apps/v1
kind: Deployment
metadata:
    labels:
        io.kompose.service: requestmapper
    name: requestmapper
spec:
    replicas: 1
    selector:
        matchLabels:
            io.kompose.service: requestmapper
    template:
        metadata:
            labels:
                io.kompose.service: requestmapper
        spec:
            containers:
                - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/mailchimp:requestmapper
                    name: requestmapper
                    ports:
                        - containerPort: 5002
                    imagePullPolicy: IfNotPresent
            restartPolicy: Always
            imagePullSecrets:
                - name: regcred