apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: ratings
  name: ratings
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ratings
  template:
    metadata:
      labels:
        io.kompose.service: ratings
    spec:
      containers:
        - image: ${AWS_ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/netflix:ratings
          name: ratings
          ports:
            - containerPort: 5009
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred